runtime: nodejs20

env: standard

instance_class: F2

automatic_scaling:
  min_instances: 0
  max_instances: 10
  target_cpu_utilization: 0.65

env_variables:
  NODE_ENV: "production"
  PORT: "8080"

handlers:
- url: /.*
  script: auto
  secure: always
  redirect_http_response_code: 301

# Include necessary files
includes:
- server/

# Exclude unnecessary files
skip_files:
- ^(.*/)?\.git/.*$
- ^(.*/)?\.gitignore$
- ^(.*/)?\.env$
- ^(.*/)?node_modules/.*$
- ^client/src/.*$
- ^client/public/.*$
- ^(.*/)?\.md$
- ^(.*/)?\.sql$
